In [32]:
import numpy as np

In [33]:
old_train_file = '/home/nithya/Desktop/voicing.npz'
new_train_file = '/home/nithya/Desktop/SSvoicing.npz'

In [34]:
old_train = np.load(old_train_file)
new_train = np.load(new_train_file)

In [35]:
#a = list(np.reshape(np.arange(8), (2, 4))) * [1, 1, 2, 2]
type(old_train['X'])

numpy.ndarray

In [36]:
old_train_X = (old_train['X'] * np.array([ 1.94692837e+03,  2.66000000e+02,  2.04703600e+01,  9.96590000e-01,
        1.19579000e+00, -1.10491000e+00,  3.62282900e+01,  1.03258700e+01] - np.array([-550.     ,    0.     ,  -80.     ,   -0.87502,   -2.98485,
         -3.36789,  -14.11584, -200.     ]))) + np.array([-550.     ,    0.     ,  -80.     ,   -0.87502,   -2.98485,
         -3.36789,  -14.11584, -200.     ])
new_train_X = (new_train['X'] * (np.array([ 1.94692837e+03,  3.19000000e+02,  2.04695600e+01,  1.00000000e+00,
        2.89285000e+00, -4.28100000e-01,  3.94103000e+01,  1.16774200e+01]) - np.array([-550.     ,    0.     ,  -80.     ,   -1.     ,   -3.51788,
        -19.61734,  -28.48101, -200.     ]))) + np.array([-550.     ,    0.     ,  -80.     ,   -1.     ,   -3.51788,
        -19.61734,  -28.48101, -200.     ])
old_train_X = np.round(old_train_X)
new_train_X = np.round(new_train_X)

# old_train_X = old_train['X']
# new_train_X = new_train['X']

In [40]:
old_train_X[0][0]

array([-550.,   36.,  -16.,    1.,   -1.,   -3.,   16., -200.])

In [39]:
new_train_X[0][0]

array([-550.,    0.,  -68.,    0.,    0.,   -9.,    0.,    6.])

In [31]:
for row in range(old_train_X.shape[0]):
    if(len(np.where((new_train_X == old_train_X[row]).all(axis=(1, 2)))) != 1):
        print(row)

In [82]:
#(new_train_X == old_train_X[0]).all(axis=(1, 2)).sum()

In [83]:
np.where((new_train_X[:, 0, 0]) == -333.)

(array([ 909, 2756]),)

In [72]:
inds = np.where(new_train_X[2756] != old_train_X[0])[0]

In [73]:
old_train_X[0, inds, 0], new_train_X[2756, inds, 0]

(array([], dtype=float64), array([], dtype=float64))

In [74]:
inds

array([], dtype=int64)