In [1]:
import numpy as np

In [27]:
file = '../Seqs/finalData/voicing/easy_1/AG-orig.npz'

In [28]:
vals = np.load(file)

In [29]:
vals['X_train'].shape

(5590, 1200, 8)

In [30]:
vals['X_test'].shape

(972, 1200, 8)

In [31]:
vals['y_train'].shape

(5590, 1)

In [32]:
vals['y_test'].shape

(972, 1)

In [33]:
(np.isnan(vals['X_train'])).sum()

0

In [34]:
(np.isnan(vals['X_test'])).sum()

0

In [35]:
from keras.utils import to_categorical

y = to_categorical(vals['y_train'])

In [36]:
np.min(vals['X_train'], axis=(0, 1))

array([-550.     ,    0.     ,  -80.     ,   -0.87502,   -2.98485,
         -3.36789,  -14.11584, -200.     ])

In [37]:
np.max(vals['X_train'], axis=(0, 1))

array([ 1.94692837e+03,  2.66000000e+02,  2.04703600e+01,  9.96590000e-01,
        1.19579000e+00, -1.10491000e+00,  3.62282900e+01,  1.03258700e+01])

In [88]:
vals['X_train'][0, :, 1]

array([-68.16777, -68.27518, -67.98596, ...,   4.2689 ,   4.35855,
         4.16574])